### ISSUE TITLE
请问这是哪门双创课？

### ISSUE THREAD

**Issue by ProgrameThinking** [kasyva/kasyva.github.io#1]

**Comment by kasyva** [comment]
是2022级大一的创新创业实践课

**Comment by ProgrameThinking** [comment]
课程名字是什么呢？感觉这门课可以学点有意思的东西

**Comment by kasyva** [comment]
名字就是这个^_^
或许这门课并不是任选课，它在计院课表上显示的是选修，但开学时是默认被选上的。有模糊的印象是课程老师曾经提到，这门课程在以往的年级不是在大一开课，而是之后的学年。
课程的确很有意思，比较注重实践而非理论~

**Comment by ProgrameThinking** [comment]
哦，感谢
